---
applications:
  - name: podinfo
    namespace: argocd
    project: default
    sources:
      - chart: podinfo
        repoURL: https://stefanprodan.github.io/podinfo
        targetRevision: 6.5.3
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        prune: false
        selfHeal: true
